export const Usertypes = {
  SET_PROFILE_INFO: "SET_PROFILE_INFO",
  SET_USER_TOKENS: "SET_USER_TOKENS",
  SET_CURRENT_PORTFOLIO: "SET_CURRENT_PORTFOLIO"
};
export const symbolTypes = {
  SET_MUTUAL_FUND: "SET_MUTUAL_FUND",
  SET_STOCK: "SET_STOCK",
  SET_FOREX: "SET_FOREX",
  SET_COMMODITY: "SET_COMMODITY",
  SET_TODOLIST: "SET_TODOLIST",

};

export const portfolioTypes = {
  SET_CURRENT_PORTFOLIO: "SET_CURRENT_PORTFOLIO",
  SET_ALL_PORTFOLIO: "SET_ALL_PORTFOLIO",
  SET_TODOLIST: "SET_TODOLIST",
};

export const TodoTypes = {
  SET_TODOLIST: "SET_TODOLIST",
};
